# This is a TOML document. Boom
[discovery]
    nodes = ["127.0.0.1:7171"]

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["10.2.19.22:9092","10.2.19.23:9092"]
